### ISSUE TITLE
Allow use without non finalized ES syntax

### ISSUE THREAD

**Issue by mlarcher** [CosticaPuntaru/redux-form-validation#1]
This project looks very appealing, but uses stage1 EcmaScript proposals (decorators, object spread). Those are subject to change (regardless of how likely it is), and using them for production goes against our company policy.
Is there any chance you can alter the syntax used in this module so that it relies only on the latest official EcmaScript standard (ES6)?

**Comment by CosticaPuntaru** [comment]
you can use it without using object spread.
generateValidations returns an object with 3 keys
source code:

``` javascript
export function generateValidation(validationConfig) {
    return {
        asyncValidate: generateAsyncValidation(validationConfig),
        asyncBlurFields: generateAsyncBlurFields(validationConfig),
        fields: Object.keys(validationConfig)
    }
}
```

so you can do this:

``` javascript

var temp = generateValidation(validations);
reduxForm({
     form: 'contact',
     asyncValidate: temp.asyncValidate,
     asyncBlurFields: temp.asyncBlurFields,
     fields: temp.fields,
   })(YourComponent)
```
