### ISSUE TITLE
Peer Dependency error with redux-form

### ISSUE THREAD

**Issue by shawnmclean** [CosticaPuntaru/redux-form-validation#11]
I have `redux-form@5.3.1` installed, when I try to install the latest `redux-form-validation` (v0.0.7), I am getting an unmet peer dependency.

I have tried this on npm 2.x and 3.x.

package:

```
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^15.2.0",
    "react-redux": "^4.4.5",
    "redux": "^3.5.2",
    "redux-form": "^5.3.1",
    "redux-form-validation": "0.0.7"
  }
}
```

error:

```
+-- UNMET PEER DEPENDENCY redux-form@5.3.1
`-- redux-form-validation@0.0.7
  `-- valid-url@1.0.9

npm WARN redux-form-validation@0.0.7 requires a peer of redux-form@^4.1.8 but none was installed.
npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.
```

Is this an issue with this library? I have other libraries specifying a dependency and I have a higher version installed and it throws no error.

**Comment by CosticaPuntaru** [comment]
Ignoring the warning, dose it work properly?

**Comment by shawnmclean** [comment]
It does work properly. Its the build system thats using that warning to throw an error.

**Comment by shawnmclean** [comment]
I did a fork, updated the peerdependency version to `^5.3.1` and it works. (I still don't know why this error was thrown).

My other option was to downgrade the `redux-form` library to exactly `4.1.8`, which breaks stuff for me.

**Comment by CosticaPuntaru** [comment]
i've updated the peerdependency to allow 4.x and 5.x, you should be fine now
