### ISSUE TITLE
Validation messages

### ISSUE THREAD

**Issue by alexeybondarenko** [CosticaPuntaru/redux-form-validation#12]
It could be useful to be able to store validation messages inside module.

**Comment by alexeybondarenko** [comment]
Can I receive value of the validation property inside error message?

For example

``` js
<li when="minLength">
  this field must have at least {field.error.minLength.value} characters
</li>
```

**Comment by alexeybondarenko** [comment]
I've found the simple solution

```
['required','min','max','minLength','maxLength','pattern','email'].forEach(function (item) {
    addValidation(item, function (field, value, prop) {
        return basicValidations[item].apply(this, arguments) ? {
            value,
            prop
        } : false;
    });
});
```

**Comment by alexeybondarenko** [comment]
How can I display error messages from several fields in one place?

**Comment by CosticaPuntaru** [comment]
This is made from two parts.  The validation and the renderer, you can create your ouwn custom renderer, see https://github.com/CosticaPuntaru/redux-form-validation/blob/master/src/form-messages/index.js

**Comment by CosticaPuntaru** [comment]
And for the value and the prop you break other functionalitys if you do that( if you don't need them is fine).  But you have the value of the field, cuz you render the message under it and the prop from the config, i don't know how you have your code structured but usualy you have moth in the same scope as the message....
