### ISSUE TITLE
Unable to resolve path to module 'redux-form-validation'

### ISSUE THREAD

**Issue by vitaliykoziy** [CosticaPuntaru/redux-form-validation#13]
Hi.
I use ESlint. And ESlint displayed this error
`error  Unable to resolve path to module 'redux-form-validation'  import/no-unresolved`

I did import of redux-form-validation
`import FormMessages, { generateValidation } from 'redux-form-validation';`

For example 
`import { reduxForm } from 'redux-form';` works fine.

P.S. Validation works fine, but ESlint displayed that error.

How to resolve this issue?

**Comment by CosticaPuntaru** [comment]
Try to import it from the file directly
`import  {generateValidation} from 'redux-form-validation/src/validation.js';`
