### ISSUE TITLE
Server side validation

### ISSUE THREAD

**Issue by alexeybondarenko** [CosticaPuntaru/redux-form-validation#15]
Is it possible to use `redux-form-validation` with server-side validation? I mean the case, when server return some codes of errors, that correspond with the validation rules on client side, such as `required`, `minlength`, etc.

**Comment by CosticaPuntaru** [comment]
i did a example for you, hope it helps: https://github.com/CosticaPuntaru/redux-form-validation/blob/master/examples/src/dynamic-validation.js
If its not what you need please ask again.

**Comment by alexeybondarenko** [comment]
Thank you for example. I didn't understand how I could use it in this case.

 For example, you have API response: 

``` js
{
 errors: {
  nickname: ['nickname_exist']
 }
}
```

How can I show  `nickname_exist` error message?

**Comment by CosticaPuntaru** [comment]
oh, i didn't got you at first.

you need this:

```
{
...otherValidations,
 promise:function (fieldName, fieldValue, dispatch){
         return fetch("yourapi/checkusername?name="+fieldValue)
       }
     },
}
```
