### ISSUE TITLE
Errors on install

### ISSUE THREAD

**Issue by anthonybrown** [CosticaPuntaru/redux-form-validation#18]
I just found your project and did the `npm i -d && npm start` in the main directory and in the example directory. This is from the terminal
![screenshot 2016-10-20 05 39 09](https://cloud.githubusercontent.com/assets/1719818/19554809/40f26b8c-9688-11e6-8c19-1a81e660f495.png)

**Comment by agnellvj** [comment]
There is a peer dependency on an older version of redux-form on any version that is 4.x or 5.x. Current redux-form version is 6.x

**Comment by CosticaPuntaru** [comment]
fixed the issue in release 1.0.0
