### ISSUE TITLE
Promise validation never sending the dispatch function

### ISSUE THREAD

**Issue by davidcurras** [CosticaPuntaru/redux-form-validation#9]
I'm getting an error when trying to use the dispatch function for email asyncValidation
`Uncaught TypeError: dispatch is not a function`
I've sent a PR with the fix
https://github.com/CosticaPuntaru/redux-form-validation/pull/8

**Comment by CosticaPuntaru** [comment]
fixed, thx for the issue and PR, i've added a test for it.
